package com.lucas.specterutils.API;

import org.bukkit.inventory.*;
import org.bukkit.*;
import org.bukkit.entity.*;
import org.bukkit.block.*;

public enum ItemName {
	AIR__0("AIR__0", 0, "Ar"), STONE__0("STONE__0", 1, "Pedra"), STONE__1("STONE__1", 2, "Granito"),
	STONE__2("STONE__2", 3, "Granito polido"), STONE__3("STONE__3", 4, "Diorito"),
	STONE__4("STONE__4", 5, "Diorito polido"), STONE__5("STONE__5", 6, "Andesito"),
	STONE__6("STONE__6", 7, "Andesito polido"), GRASS__0("GRASS__0", 8, "Bloco de grama"),
	DIRT__0("DIRT__0", 9, "Terra"), DIRT__1("DIRT__1", 10, "Terra grossa"), DIRT__2("DIRT__2", 11, "Podzol"),
	COBBLESTONE__0("COBBLESTONE__0", 12, "Pedregulho"), WOOD__0("WOOD__0", 13, "T\u00e1buas de carvalho"),
	WOOD__1("WOOD__1", 14, "T\u00e1buas de pinheiro"), WOOD__2("WOOD__2", 15, "T\u00e1buas de eucalipto"),
	WOOD__3("WOOD__3", 16, "T\u00e1buas de madeira da selva"), WOOD__4("WOOD__4", 17, "T\u00e1buas de ac\u00e1cia"),
	WOOD__5("WOOD__5", 18, "T\u00e1buas de carvalho escuro"), SAPLING__0("SAPLING__0", 19, "Muda de carvalho"),
	SAPLING__1("SAPLING__1", 20, "Muda de pinheiro"), SAPLING__2("SAPLING__2", 21, "Muda de eucalipto"),
	SAPLING__3("SAPLING__3", 22, "Muda de \u00e1rvore da selva"), SAPLING__4("SAPLING__4", 23, "Muda de ac\u00e1cia"),
	SAPLING__5("SAPLING__5", 24, "Muda de carvalho escuro"), BEDROCK__0("BEDROCK__0", 25, "Rocha matriz"),
	WATER__0("WATER__0", 26, "\u00c1gua"), STATIONARY_WATER__0("STATIONARY_WATER__0", 27, "\u00c1gua"),
	LAVA__0("LAVA__0", 28, "Lava"), STATIONARY_LAVA__0("STATIONARY_LAVA__0", 29, "Lava"),
	SAND__0("SAND__0", 30, "Areia"), SAND__1("SAND__1", 31, "Areia vermelha"), GRAVEL__0("GRAVEL__0", 32, "Cascalho"),
	GOLD_ORE__0("GOLD_ORE__0", 33, "Min\u00e9rio de ouro"), IRON_ORE__0("IRON_ORE__0", 34, "Min\u00e9rio de ferro"),
	COAL_ORE__0("COAL_ORE__0", 35, "Min\u00e9rio de carv\u00e3o"), LOG__0("LOG__0", 36, "Maderia de carvalho"),
	LOG__1("LOG__1", 37, "Maderia de pinheiro"), LOG__2("LOG__2", 38, "Maderia de eucalipto"),
	LOG__3("LOG__3", 39, "Maderia da selva"), LEAVES__0("LEAVES__0", 40, "Folhas de carvalho"),
	LEAVES__1("LEAVES__1", 41, "Folhas de pinheiro"), LEAVES__2("LEAVES__2", 42, "Folhas de eucalipto"),
	LEAVES__3("LEAVES__3", 43, "Folhas da selva "), SPONGE__0("SPONGE__0", 44, "Esponja"),
	SPONGE__1("SPONGE__1", 45, "Esponja molhada"), GLASS__0("GLASS__0", 46, "Vidro"),
	LAPIS_ORE__0("LAPIS_ORE__0", 47, "Min\u00e9rio de l\u00e1pis-laz\u00fali"),
	LAPIS_BLOCK__0("LAPIS_BLOCK__0", 48, "Bloco de l\u00e1pis-laz\u00fali"), DISPENSER__0("DISPENSER__0", 49, "Ejetor"),
	SANDSTONE__0("SANDSTONE__0", 50, "Arenito"), SANDSTONE__1("SANDSTONE__1", 51, "Arenito talhado"),
	SANDSTONE__2("SANDSTONE__2", 52, "Arenito liso"), NOTE_BLOCK__0("NOTE_BLOCK__0", 53, "Bloco musical"),
	BED_BLOCK__0("BED_BLOCK__0", 54, "Cama"), POWERED_RAIL__0("POWERED_RAIL__0", 55, "Trilho el\u00e9trico"),
	DETECTOR_RAIL__0("DETECTOR_RAIL__0", 56, "Trilho detector"),
	PISTON_STICKY_BASE__0("PISTON_STICKY_BASE__0", 57, "Pist\u00e3o grudento"), WEB__0("WEB__0", 58, "Teia de Aranha"),
	LONG_GRASS__0("LONG_GRASS__0", 59, "Arbusto"), LONG_GRASS__1("LONG_GRASS__1", 60, "Grama"),
	LONG_GRASS__2("LONG_GRASS__2", 61, "Samambaia"), DEAD_BUSH__0("DEAD_BUSH__0", 62, "Arbusto Morto"),
	PISTON_BASE__0("PISTON_BASE__0", 63, "Pist\u00e3o"), PISTON_EXTENSION__0("PISTON_EXTENSION__0", 64, "Pist\u00e3o"),
	WOOL__0("WOOL__0", 65, "L\u00e3 branca"), WOOL__1("WOOL__1", 66, "L\u00e3 laranja"),
	WOOL__2("WOOL__2", 67, "L\u00e3 magenta"), WOOL__3("WOOL__3", 68, "L\u00e3 azul clara"),
	WOOL__4("WOOL__4", 69, "L\u00e3 amarela"), WOOL__5("WOOL__5", 70, "L\u00e3 verde-lim\u00e3o"),
	WOOL__6("WOOL__6", 71, "L\u00e3 rosa"), WOOL__7("WOOL__7", 72, "L\u00e3 cinza"),
	WOOL__8("WOOL__8", 73, "L\u00e3 cinza clara"), WOOL__9("WOOL__9", 74, "L\u00e3 ciano"),
	WOOL__10("WOOL__10", 75, "L\u00e3 roxa"), WOOL__11("WOOL__11", 76, "L\u00e3 azul"),
	WOOL__12("WOOL__12", 77, "L\u00e3 marrom"), WOOL__13("WOOL__13", 78, "L\u00e3 verde"),
	WOOL__14("WOOL__14", 79, "L\u00e3 vermelha"), WOOL__15("WOOL__15", 80, "L\u00e3 preta"),
	PISTON_MOVING_PIECE__0("PISTON_MOVING_PIECE__0", 81, "Pist\u00e3o"),
	YELLOW_FLOWER__0("YELLOW_FLOWER__0", 82, "Dente-de-Le\u00e3o"), RED_ROSE__0("RED_ROSE__0", 83, "Popula"),
	RED_ROSE__1("RED_ROSE__1", 84, "Orqu\u00eddea azul"), RED_ROSE__2("RED_ROSE__2", 85, "Hort\u00eancia"),
	RED_ROSE__3("RED_ROSE__3", 86, "Flor silvestre azul"), RED_ROSE__4("RED_ROSE__4", 87, "Tulipa vermelha"),
	RED_ROSE__5("RED_ROSE__5", 88, "Tulipa laranja"), RED_ROSE__6("RED_ROSE__6", 89, "Tulipa branca"),
	RED_ROSE__7("RED_ROSE__7", 90, "Tulipa rosa"), RED_ROSE__8("RED_ROSE__8", 91, "Margarida"),
	BROWN_MUSHROOM__0("BROWN_MUSHROOM__0", 92, "Cogumelo"), RED_MUSHROOM__0("RED_MUSHROOM__0", 93, "Cogumelo"),
	GOLD_BLOCK__0("GOLD_BLOCK__0", 94, "Bloco de ouro"), IRON_BLOCK__0("IRON_BLOCK__0", 95, "Bloco de ferro"),
	DOUBLE_STEP__0("DOUBLE_STEP__0", 96, "Laje dupla de pedra"),
	DOUBLE_STEP__1("DOUBLE_STEP__1", 97, "Laje dupla de arenito"),
	DOUBLE_STEP__2("DOUBLE_STEP__2", 98, "Laje dupla de madeira"),
	DOUBLE_STEP__3("DOUBLE_STEP__3", 99, "Laje dupla de pedregulho"),
	DOUBLE_STEP__4("DOUBLE_STEP__4", 100, "Laje dupla de tijolos"),
	DOUBLE_STEP__5("DOUBLE_STEP__5", 101, "Laje dupla de tijolos de pedra"),
	DOUBLE_STEP__6("DOUBLE_STEP__6", 102, "Laje dupla de tijolos do Nether"),
	DOUBLE_STEP__7("DOUBLE_STEP__7", 103, "Laje dupla de quartzo"), STEP__0("STEP__0", 104, "Laje de pedra"),
	STEP__1("STEP__1", 105, "Laje de arenito"), STEP__2("STEP__2", 106, "Laje de madeira"),
	STEP__3("STEP__3", 107, "Laje de pedregulho"), STEP__4("STEP__4", 108, "Laje de tijolos"),
	STEP__5("STEP__5", 109, "Laje de tijolos de pedra"), STEP__6("STEP__6", 110, "Laje de tijolos do Nether"),
	STEP__7("STEP__7", 111, "Laje de quartzo"), BRICK__0("BRICK__0", 112, "Tijolos"), TNT__0("TNT__0", 113, "Dinamite"),
	BOOKSHELF__0("BOOKSHELF__0", 114, "Estante"), MOSSY_COBBLESTONE__0("MOSSY_COBBLESTONE__0", 115, "Pedra com musgo"),
	OBSIDIAN__0("OBSIDIAN__0", 116, "Obsidiana"), TORCH__0("TORCH__0", 117, "Tocha"), FIRE__0("FIRE__0", 118, "Fogo"),
	MOB_SPAWNER__0("MOB_SPAWNER__0", 119, "Gerador de monstros"),
	WOOD_STAIRS__0("WOOD_STAIRS__0", 120, "Escadas de carvalho"), CHEST__0("CHEST__0", 121, "Ba\u00fa"),
	REDSTONE_WIRE__0("REDSTONE_WIRE__0", 122, "P\u00f3 de Redstone"),
	DIAMOND_ORE__0("DIAMOND_ORE__0", 123, "Min\u00e9rio de diamante"),
	DIAMOND_BLOCK__0("DIAMOND_BLOCK__0", 124, "Bloco de diamante"),
	WORKBENCH__0("WORKBENCH__0", 125, "Bancada de trabalho"), CROPS__0("CROPS__0", 126, "Planta\u00e7\u00e3o"),
	SOIL__0("SOIL__0", 127, "Terra arada"), FURNACE__0("FURNACE__0", 128, "Fornalha"),
	BURNING_FURNACE__0("BURNING_FURNACE__0", 129, "Fornalha"), SIGN_POST__0("SIGN_POST__0", 130, "Placa"),
	WOODEN_DOOR__0("WOODEN_DOOR__0", 131, "Porta de madeira"), LADDER__0("LADDER__0", 132, "Escada"),
	RAILS__0("RAILS__0", 133, "Trilho"), COBBLESTONE_STAIRS__0("COBBLESTONE_STAIRS__0", 134, "Escadas de pedra"),
	WALL_SIGN__0("WALL_SIGN__0", 135, "Placa"), LEVER__0("LEVER__0", 136, "Alavanca"),
	STONE_PLATE__0("STONE_PLATE__0", 137, "Placa de press\u00e3o de pedra"),
	IRON_DOOR_BLOCK__0("IRON_DOOR_BLOCK__0", 138, "Porta de ferro"),
	WOOD_PLATE__0("WOOD_PLATE__0", 139, "Placa de press\u00e3o de madeira"),
	REDSTONE_ORE__0("REDSTONE_ORE__0", 140, "Min\u00e9rio de redstone"),
	GLOWING_REDSTONE_ORE__0("GLOWING_REDSTONE_ORE__0", 141, "Min\u00e9rio de redstone"),
	REDSTONE_TORCH_OFF__0("REDSTONE_TORCH_OFF__0", 142, "Tocha de redstone"),
	REDSTONE_TORCH_ON__0("REDSTONE_TORCH_ON__0", 143, "Tocha de restone"),
	STONE_BUTTON__0("STONE_BUTTON__0", 144, "Bot\u00e3o"), SNOW__0("SNOW__0", 145, "Neve"),
	ICE__0("ICE__0", 146, "Gelo"), SNOW_BLOCK__0("SNOW_BLOCK__0", 147, "Neve"), CACTUS__0("CACTUS__0", 148, "Cacto"),
	CLAY__0("CLAY__0", 149, "Argila"), SUGAR_CANE_BLOCK__0("SUGAR_CANE_BLOCK__0", 150, "Canas de a\u00e7ucar"),
	JUKEBOX__0("JUKEBOX__0", 151, "Jukebox"), FENCE__0("FENCE__0", 152, "Cerca de carvalho"),
	PUMPKIN__0("PUMPKIN__0", 153, "Ab\u00f3bora"), NETHERRACK__0("NETHERRACK__0", 154, "Rocha do Nether"),
	SOUL_SAND__0("SOUL_SAND__0", 155, "Areia de almas"), GLOWSTONE__0("GLOWSTONE__0", 156, "Pedra luminosa"),
	PORTAL__0("PORTAL__0", 157, "Portal"), JACK_O_LANTERN__0("JACK_O_LANTERN__0", 158, "Ab\u00f3bora de Halloween"),
	CAKE_BLOCK__0("CAKE_BLOCK__0", 159, "Bolo"), DIODE_BLOCK_OFF__0("DIODE_BLOCK_OFF__0", 160, "Repetidor de Redstone"),
	DIODE_BLOCK_ON__0("DIODE_BLOCK_ON__0", 161, "Repetidor de Redstone"),
	STAINED_GLASS__0("STAINED_GLASS__0", 162, "Vidro tingido de branco"),
	STAINED_GLASS__1("STAINED_GLASS__1", 163, "Vidro tingido de laranja"),
	STAINED_GLASS__2("STAINED_GLASS__2", 164, "Vidro tingido de magenta"),
	STAINED_GLASS__3("STAINED_GLASS__3", 165, "Vidro tingido de azul claro"),
	STAINED_GLASS__4("STAINED_GLASS__4", 166, "Vidro tingido de amarelo"),
	STAINED_GLASS__5("STAINED_GLASS__5", 167, "Vidro tingido de verde lim\u00e3o"),
	STAINED_GLASS__6("STAINED_GLASS__6", 168, "Vidro tingido de rosa"),
	STAINED_GLASS__7("STAINED_GLASS__7", 169, "Vidro tingido de cinza"),
	STAINED_GLASS__8("STAINED_GLASS__8", 170, "Vidro tingido de cinza claro"),
	STAINED_GLASS__9("STAINED_GLASS__9", 171, "Vidro tingido de ciano"),
	STAINED_GLASS__10("STAINED_GLASS__10", 172, "Vidro tingido de lil\u00e1s"),
	STAINED_GLASS__11("STAINED_GLASS__11", 173, "Vidro tingido de azul"),
	STAINED_GLASS__12("STAINED_GLASS__12", 174, "Vidro tingido de marrom"),
	STAINED_GLASS__13("STAINED_GLASS__13", 175, "Vidro tingido de verde"),
	STAINED_GLASS__14("STAINED_GLASS__14", 176, "Vidro tingido de vermelho"),
	STAINED_GLASS__15("STAINED_GLASS__15", 177, "Vidro tingido de preto"),
	LOCKED_CHEST__0("LOCKED_CHEST__0", 178, "Ba\u00fa trancado"),
	TRAP_DOOR__0("TRAP_DOOR__0", 179, "Al\u00e7ap\u00e3o de madeira"),
	MONSTER_EGGS__0("MONSTER_EGGS__0", 180, "Ovo de monstro de pedra"),
	MONSTER_EGGS__1("MONSTER_EGGS__1", 181, "Ovo de monstro de pedregulho"),
	MONSTER_EGGS__2("MONSTER_EGGS__2", 182, "Ovo de monstro de tijolos de pedra"),
	MONSTER_EGGS__3("MONSTER_EGGS__3", 183, "Ovo de monstro de tijolos de pedra com musgo"),
	MONSTER_EGGS__4("MONSTER_EGGS__4", 184, "Ovo de monstro de tijolos de pedra rachados"),
	MONSTER_EGGS__5("MONSTER_EGGS__5", 185, "Ovo de monstro de tijolos de pedra talhados"),
	SMOOTH_BRICK__0("SMOOTH_BRICK__0", 186, "Tijolos de pedra"),
	SMOOTH_BRICK__1("SMOOTH_BRICK__1", 187, "Tijolos de pedra com musgo"),
	SMOOTH_BRICK__2("SMOOTH_BRICK__2", 188, "Tijolos de pedra rachados"),
	SMOOTH_BRICK__3("SMOOTH_BRICK__3", 189, "Tijolos de pedra talhados"),
	HUGE_MUSHROOM_1__0("HUGE_MUSHROOM_1__0", 190, "Bloco de cogumelo"),
	HUGE_MUSHROOM_2__0("HUGE_MUSHROOM_2__0", 191, "Bloco de cogumelo"),
	IRON_FENCE__0("IRON_FENCE__0", 192, "Barras de ferro"), THIN_GLASS__0("THIN_GLASS__0", 193, "Painel de vidro"),
	MELON_BLOCK__0("MELON_BLOCK__0", 194, "Melancia"),
	PUMPKIN_STEM__0("PUMPKIN_STEM__0", 195, "Planta\u00e7\u00e3o de ab\u00f3bora"),
	MELON_STEM__0("MELON_STEM__0", 196, "Planta\u00e7\u00e3o de melancia"), VINE__0("VINE__0", 197, "Vinhas"),
	FENCE_GATE__0("FENCE_GATE__0", 198, "Port\u00e3o de carvalho"),
	BRICK_STAIRS__0("BRICK_STAIRS__0", 199, "Escadas de tijolos"),
	SMOOTH_STAIRS__0("SMOOTH_STAIRS__0", 200, "Escadas de tijolos de pedra"), MYCEL__0("MYCEL__0", 201, "Mic\u00e9lio"),
	WATER_LILY__0("WATER_LILY__0", 202, "Vit\u00f3ria-R\u00e9gia"),
	NETHER_BRICK__0("NETHER_BRICK__0", 203, "Tijolos do Nether"),
	NETHER_FENCE__0("NETHER_FENCE__0", 204, "Cerca de tijolos do Nether"),
	NETHER_BRICK_STAIRS__0("NETHER_BRICK_STAIRS__0", 205, "Escadas de tijolos do Nether"),
	NETHER_WARTS__0("NETHER_WARTS__0", 206, "Planta\u00e7\u00e3o de fungo do Nether"),
	ENCHANTMENT_TABLE__0("ENCHANTMENT_TABLE__0", 207, "Mesa de encantamentos"),
	BREWING_STAND__0("BREWING_STAND__0", 208, "Suporte de po\u00e7\u00f5es"),
	CAULDRON__0("CAULDRON__0", 209, "Caldeir\u00e3o"), ENDER_PORTAL__0("ENDER_PORTAL__0", 210, "Portal"),
	ENDER_PORTAL_FRAME__0("ENDER_PORTAL_FRAME__0", 211, "Portal do fim"),
	ENDER_STONE__0("ENDER_STONE__0", 212, "Pedra do fim"), DRAGON_EGG__0("DRAGON_EGG__0", 213, "Ovo do drag\u00e3o"),
	REDSTONE_LAMP_OFF__0("REDSTONE_LAMP_OFF__0", 214, "L\u00e2mpada de redstone"),
	REDSTONE_LAMP_ON__0("REDSTONE_LAMP_ON__0", 215, "L\u00e2mpada de redstone"),
	WOOD_DOUBLE_STEP__0("WOOD_DOUBLE_STEP__0", 216, "Laje dupla de carvalho"),
	WOOD_DOUBLE_STEP__1("WOOD_DOUBLE_STEP__1", 217, "Laje dupla de pinheiro"),
	WOOD_DOUBLE_STEP__2("WOOD_DOUBLE_STEP__2", 218, "Laje dupla de eucalipto"),
	WOOD_DOUBLE_STEP__3("WOOD_DOUBLE_STEP__3", 219, "Laje dupla de madeira da selva"),
	WOOD_DOUBLE_STEP__4("WOOD_DOUBLE_STEP__4", 220, "Laje dupla de ac\u00e1cia"),
	WOOD_DOUBLE_STEP__5("WOOD_DOUBLE_STEP__5", 221, "Laje dupla de carvalho escuro"),
	WOOD_STEP__0("WOOD_STEP__0", 222, "Laje de carvalho"), WOOD_STEP__1("WOOD_STEP__1", 223, "Laje de pinheiro"),
	WOOD_STEP__2("WOOD_STEP__2", 224, "Laje de eucalipto"),
	WOOD_STEP__3("WOOD_STEP__3", 225, "Laje de madeira da selva"),
	WOOD_STEP__4("WOOD_STEP__4", 226, "Laje de ac\u00e1cia"),
	WOOD_STEP__5("WOOD_STEP__5", 227, "Laje de carvalho escuro"), COCOA__0("COCOA__0", 228, "Cacau"),
	SANDSTONE_STAIRS__0("SANDSTONE_STAIRS__0", 229, "Escadas de arenito"),
	EMERALD_ORE__0("EMERALD_ORE__0", 230, "Min\u00e9rio de esmeralda"),
	ENDER_CHEST__0("ENDER_CHEST__0", 231, "Ba\u00fa do fim"),
	TRIPWIRE_HOOK__0("TRIPWIRE_HOOK__0", 232, "Gancho de armadilha"),
	TRIPWIRE__0("TRIPWIRE__0", 233, "Gancho de armadilha"),
	EMERALD_BLOCK__0("EMERALD_BLOCK__0", 234, "Bloco de esmeralda"),
	SPRUCE_WOOD_STAIRS__0("SPRUCE_WOOD_STAIRS__0", 235, "Escadas de pinheiro"),
	BIRCH_WOOD_STAIRS__0("BIRCH_WOOD_STAIRS__0", 236, "Escadas de eucalipto"),
	JUNGLE_WOOD_STAIRS__0("JUNGLE_WOOD_STAIRS__0", 237, "Escadas de madeira da selva"),
	COMMAND__0("COMMAND__0", 238, "Bloco de comando"), BEACON__0("BEACON__0", 239, "Sinalizador"),
	COBBLE_WALL__0("COBBLE_WALL__0", 240, "Parede de pedregulho"),
	COBBLE_WALL__1("COBBLE_WALL__1", 241, "Parede de pedregulho com musgo"),
	FLOWER_POT__0("FLOWER_POT__0", 242, "Vaso de flor"), CARROT__0("CARROT__0", 243, "Planta\u00e7\u00e3o de cenouras"),
	POTATO__0("POTATO__0", 244, "Planta\u00e7\u00e3o de batatas"), WOOD_BUTTON__0("WOOD_BUTTON__0", 245, "Bot\u00e3o"),
	SKULL__0("SKULL__0", 246, "Cabe\u00e7a"), ANVIL__0("ANVIL__0", 247, "Bigorna"),
	ANVIL__1("ANVIL__1", 248, "Bigorna ligeiramente danificada"), ANVIL__2("ANVIL__2", 249, "Bigorna muito danificada"),
	TRAPPED_CHEST__0("TRAPPED_CHEST__0", 250, "Ba\u00fa com armadilha"),
	GOLD_PLATE__0("GOLD_PLATE__0", 251, "Placa de press\u00e3o de pesagem (leve)"),
	IRON_PLATE__1("IRON_PLATE__1", 252, "Placa de press\u00e3o de pesagem (pesada)"),
	REDSTONE_COMPARATOR_OFF__0("REDSTONE_COMPARATOR_OFF__0", 253, "Comparador de redstone"),
	REDSTONE_COMPARATOR_ON__0("REDSTONE_COMPARATOR_ON__0", 254, "Comparador de redstone"),
	DAYLIGHT_DETECTOR__0("DAYLIGHT_DETECTOR__0", 255, "Sensor de luz solar"),
	REDSTONE_BLOCK__0("REDSTONE_BLOCK__0", 256, "Bloco de redstone"),
	QUARTZ_ORE__0("QUARTZ_ORE__0", 257, "Min\u00e9rio de quartzo"), HOPPER__0("HOPPER__0", 258, "Funil"),
	QUARTZ_BLOCK__0("QUARTZ_BLOCK__0", 259, "Bloco de quartzo"),
	QUARTZ_BLOCK__1("QUARTZ_BLOCK__1", 260, "Bloco de quartzo talhado"),
	QUARTZ_BLOCK__2("QUARTZ_BLOCK__2", 261, "Pilar de quartzo"),
	QUARTZ_STAIRS__0("QUARTZ_STAIRS__0", 262, "Escadas de quartzo"),
	ACTIVATOR_RAIL("ACTIVATOR_RAIL", 263, "Trilho ativador"), DROPPER("DROPPER", 264, "Liberador"),
	STAINED_CLAY__0("STAINED_CLAY__0", 265, "Argila tingida de branco"),
	STAINED_CLAY__1("STAINED_CLAY__1", 266, "Argila tingida de laranja"),
	STAINED_CLAY__2("STAINED_CLAY__2", 267, "Argila tingida de magenta"),
	STAINED_CLAY__3("STAINED_CLAY__3", 268, "Argila tingida de azul claro"),
	STAINED_CLAY__4("STAINED_CLAY__4", 269, "Argila tingida de amarelo"),
	STAINED_CLAY__5("STAINED_CLAY__5", 270, "Argila tingida de verde lim\u00e3o"),
	STAINED_CLAY__6("STAINED_CLAY__6", 271, "Argila tingida de rosa"),
	STAINED_CLAY__7("STAINED_CLAY__7", 272, "Argila tingida de cinza"),
	STAINED_CLAY__8("STAINED_CLAY__8", 273, "Argila tingida de cinza claro"),
	STAINED_CLAY__9("STAINED_CLAY__9", 274, "Argila tingida de ciano"),
	STAINED_CLAY__10("STAINED_CLAY__10", 275, "Argila tingida de lil\u00e1s"),
	STAINED_CLAY__11("STAINED_CLAY__11", 276, "Argila tingida de azul"),
	STAINED_CLAY__12("STAINED_CLAY__12", 277, "Argila tingida de marrom"),
	STAINED_CLAY__13("STAINED_CLAY__13", 278, "Argila tingida de verde"),
	STAINED_CLAY__14("STAINED_CLAY__14", 279, "Argila tingida de vermelho"),
	STAINED_CLAY__15("STAINED_CLAY__15", 280, "Argila tingida de preto"),
	STAINED_GLASS_PANE__0("STAINED_GLASS_PANE__0", 281, "Painel de vidro tingido de branco"),
	STAINED_GLASS_PANE__1("STAINED_GLASS_PANE__1", 282, "Painel de vidro tingido de laranja"),
	STAINED_GLASS_PANE__2("STAINED_GLASS_PANE__2", 283, "Painel de vidro tingido de magenta"),
	STAINED_GLASS_PANE__3("STAINED_GLASS_PANE__3", 284, "Painel de vidro tingido de azul claro"),
	STAINED_GLASS_PANE__4("STAINED_GLASS_PANE__4", 285, "Painel de vidro tingido de amarelo"),
	STAINED_GLASS_PANE__5("STAINED_GLASS_PANE__5", 286, "Painel de vidro tingido de verde lim\u00e3o"),
	STAINED_GLASS_PANE__6("STAINED_GLASS_PANE__6", 287, "Painel de vidro tingido de rosa"),
	STAINED_GLASS_PANE__7("STAINED_GLASS_PANE__7", 288, "Painel de vidro tingido de cinza"),
	STAINED_GLASS_PANE__8("STAINED_GLASS_PANE__8", 289, "Painel de vidro tingido de cinza claro"),
	STAINED_GLASS_PANE__9("STAINED_GLASS_PANE__9", 290, "Painel de vidro tingido de ciano"),
	STAINED_GLASS_PANE__10("STAINED_GLASS_PANE__10", 291, "Painel de vidro tingido de lil\u00e1s"),
	STAINED_GLASS_PANE__11("STAINED_GLASS_PANE__11", 292, "Painel de vidro tingido de azul"),
	STAINED_GLASS_PANE__12("STAINED_GLASS_PANE__12", 293, "Painel de vidro tingido de marrom"),
	STAINED_GLASS_PANE__13("STAINED_GLASS_PANE__13", 294, "Painel de vidro tingido de verde"),
	STAINED_GLASS_PANE__14("STAINED_GLASS_PANE__14", 295, "Painel de vidro tingido de vermelho"),
	STAINED_GLASS_PANE__15("STAINED_GLASS_PANE__15", 296, "Painel de vidro tingido de preto"),
	LEAVES_2__0("LEAVES_2__0", 297, "Folhas de ac\u00e1cia"),
	LEAVES_2__1("LEAVES_2__1", 298, "Folhas de carvalho escuro"), LOG_2__0("LOG_2__0", 299, "Madeira de ac\u00e1cia"),
	LOG_2__1("LOG_2__1", 300, "Madeira de carvalho escuro"),
	ACACIA_STAIRS__0("ACACIA_STAIRS__0", 301, "Escadas de ac\u00e1cia"),
	DARK_OAK_STAIRS__0("DARK_OAK_STAIRS__0", 302, "Escadas de carvalho escuro"),
	SLIME_BLOCK__0("SLIME_BLOCK__0", 303, "Bloco de slime"), BARRIER__0("BARRIER__0", 304, "Barreira"),
	IRON_TRAPDOOR__0("IRON_TRAPDOOR__0", 305, "Al\u00e7ap\u00e3o de ferro"),
	PRISMARINE__0("PRISMARINE__0", 306, "Prismarinho"), PRISMARINE__1("PRISMARINE__1", 307, "Tijolos de prismarinho"),
	PRISMARINE__2("PRISMARINE__2", 308, "Prismarinho escuro"), SEA_LANTERN__0("SEA_LANTERN__0", 309, "Lanterna do mar"),
	HAY_BLOCK__0("HAY_BLOCK__0", 310, "Fardo de feno"), CARPET__0("CARPET__0", 311, "Carpete"),
	CARPET__1("CARPET__1", 312, "Carpete laranja"), CARPET__2("CARPET__2", 313, "Carpete magenta"),
	CARPET__3("CARPET__3", 314, "Carpete azul claro"), CARPET__4("CARPET__4", 315, "Carpete amarelo"),
	CARPET__5("CARPET__5", 316, "Carpete verde lim\u00e3o"), CARPET__6("CARPET__6", 317, "Carpete rosa"),
	CARPET__7("CARPET__7", 318, "Carpete cinza"), CARPET__8("CARPET__8", 319, "Carpete cinza claro"),
	CARPET__9("CARPET__9", 320, "Carpete ciano"), CARPET__10("CARPET__10", 321, "Carpete lil\u00e1s"),
	CARPET__11("CARPET__11", 322, "Carpete azul"), CARPET__12("CARPET__12", 323, "Carpete marrom"),
	CARPET__13("CARPET__13", 324, "Carpete verde"), CARPET__14("CARPET__14", 325, "Carpete vermelho"),
	CARPET__15("CARPET__15", 326, "Carpete preto"), HARD_CLAY__0("HARD_CLAY__0", 327, "Argila endurecida"),
	COAL_BLOCK__0("COAL_BLOCK__0", 328, "Bloco de carv\u00e3o"), PACKED_ICE__0("PACKED_ICE__0", 329, "Gelo compactado"),
	DOUBLE_PLANT__0("DOUBLE_PLANT__0", 330, "Girassol"), DOUBLE_PLANT__1("DOUBLE_PLANT__1", 331, "Lil\u00e1s"),
	DOUBLE_PLANT__2("DOUBLE_PLANT__2", 332, "Grama alta"), DOUBLE_PLANT__3("DOUBLE_PLANT__3", 333, "Samambaia grande"),
	DOUBLE_PLANT__4("DOUBLE_PLANT__4", 334, "Roseira"), DOUBLE_PLANT__5("DOUBLE_PLANT__5", 335, "Pe\u00f4nia"),
	STANDING_BANNER__0("STANDING_BANNER__0", 336, "Estandarte"), WALL_BANNER__0("WALL_BANNER__0", 337, "Estandarte"),
	DAYLIGHT_DETECTOR_INVERTED__0("DAYLIGHT_DETECTOR_INVERTED__0", 338, "Sensor de luz solar"),
	RED_SANDSTONE__0("RED_SANDSTONE__0", 339, "Arenito vermelho"),
	RED_SANDSTONE__1("RED_SANDSTONE__1", 340, "Arenito vermelho talhado"),
	RED_SANDSTONE__2("RED_SANDSTONE__2", 341, "Arenito vermelho liso"),
	RED_SANDSTONE_STAIRS__0("RED_SANDSTONE_STAIRS__0", 342, "Escadas de arenito vermelho"),
	DOUBLE_STONE_SLAB2__0("DOUBLE_STONE_SLAB2__0", 343, "Laje dupla de arenito vermelho"),
	STONE_SLAB2__0("STONE_SLAB2__0", 344, "Laje de arenito vermelho"),
	SPRUCE_FENCE_GATE__0("SPRUCE_FENCE_GATE__0", 345, "Port\u00e3o de pinheiro"),
	BIRCH_FENCE_GATE__0("BIRCH_FENCE_GATE__0", 346, "Port\u00e3o de eucalipto"),
	JUNGLE_FENCE_GATE__0("JUNGLE_FENCE_GATE__0", 347, "Port\u00e3o de madeira da selva"),
	DARK_OAK_FENCE_GATE__0("DARK_OAK_FENCE_GATE__0", 348, "Port\u00e3o de carvalho escuro"),
	ACACIA_FENCE_GATE__0("ACACIA_FENCE_GATE__0", 349, "Port\u00e3o de ac\u00e1cia"),
	SPRUCE_FENCE__0("SPRUCE_FENCE__0", 350, "Cerca de pinhero"),
	BIRCH_FENCE__0("BIRCH_FENCE__0", 351, "Cerca de eucalipto"),
	JUNGLE_FENCE__0("JUNGLE_FENCE__0", 352, "Cerca de madeira da selva"),
	DARK_OAK_FENCE__0("DARK_OAK_FENCE__0", 353, "Cerca de carvalho escuro"),
	ACACIA_FENCE__0("ACACIA_FENCE__0", 354, "Cerca de ac\u00e1cia"),
	SPRUCE_DOOR__0("SPRUCE_DOOR__0", 355, "Porta de pinheiro"),
	BIRCH_DOOR__0("BIRCH_DOOR__0", 356, "Porta de eucalipto"),
	JUNGLE_DOOR__0("JUNGLE_DOOR__0", 357, "Porta de madeira da selva"),
	ACACIA_DOOR__0("ACACIA_DOOR__0", 358, "Porta de ac\u00e1cia"),
	DARK_OAK_DOOR__0("DARK_OAK_DOOR__0", 359, "Porta de carvalho escuro"),
	END_ROD__0("END_ROD__0", 360, "L\u00e2mpada do end"), CHORUS_PLANT__0("CHORUS_PLANT__0", 361, "Planta do coro"),
	CHORUS_FLOWER__0("CHORUS_FLOWER__0", 362, "Flor do coro"),
	PURPUR_BLOCK__0("PURPUR_BLOCK__0", 363, "Bloco de p\u00farpura"),
	PURPUR_PILLAR__0("PURPUR_PILLAR__0", 364, "Pilar de p\u00farpura"),
	PURPUR_STAIRS__0("PURPUR_STAIRS__0", 365, "Escadas de p\u00farpura"),
	PURPUR_DOUBLE_SLAB__0("PURPUR_DOUBLE_SLAB__0", 366, "Laje dupla de p\u00farpura"),
	PURPUR_SLAB__0("PURPUR_SLAB__0", 367, "Laje de p\u00farpura"),
	END_BRICKS__0("END_BRICKS__0", 368, "Tijolos de pedra do fim"),
	BEETROOT_BLOCK__0("BEETROOT_BLOCK__0", 369, "Planta\u00e7\u00e3o de beterraba"),
	GRASS_PATH__0("GRASS_PATH__0", 370, "Caminho de grama"), END_GATEWAY__0("END_GATEWAY__0", 371, "Portal do fim"),
	COMMAND_REPEATING__0("COMMAND_REPEATING__0", 372, "Bloco de comando em repeti\u00e7\u00e3o"),
	COMMAND_CHAIN__0("COMMAND_CHAIN__0", 373, "Bloco de comando em cadeia"),
	FROSTED_ICE__0("FROSTED_ICE__0", 374, "Gelo compactado"), MAGMA__0("MAGMA__0", 375, "Bloco de magma"),
	NETHER_WART_BLOCK__0("NETHER_WART_BLOCK__0", 376, "Bloco de fungos do Nether"),
	RED_NETHER_BRICK__0("RED_NETHER_BRICK__0", 377, "Tijolos vermelhos do Nether"),
	BONE_BLOCK__0("BONE_BLOCK__0", 378, "Bloco de ossos"),
	STRUCTURE_VOID__0("STRUCTURE_VOID__0", 379, "Vazio da estrutura"), OBSERVER__0("OBSERVER__0", 380, "Observador"),
	WHITE_SHULKER_BOX__0("WHITE_SHULKER_BOX__0", 381, "Caixa de shulker branca"),
	ORANGE_SHULKER_BOX__0("ORANGE_SHULKER_BOX__0", 382, "Caixa de shulker laranja"),
	MAGENTA_SHULKER_BOX__0("MAGENTA_SHULKER_BOX__0", 383, "Caixa de shulker magenta"),
	LIGHT_BLUE_SHULKER_BOX__0("LIGHT_BLUE_SHULKER_BOX__0", 384, "Caixa de shulker azul clara"),
	YELLOW_SHULKER_BOX__0("YELLOW_SHULKER_BOX__0", 385, "Caixa de shulker amarela"),
	LIME_SHULKER_BOX__0("LIME_SHULKER_BOX__0", 386, "Caixa de shulker verde lim\u00e3o"),
	PINK_SHULKER_BOX__0("PINK_SHULKER_BOX__0", 387, "Caixa de shulker rosa"),
	GRAY_SHULKER_BOX__0("GRAY_SHULKER_BOX__0", 388, "Caixa de shulker cinza"),
	SILVER_SHULKER_BOX__0("SILVER_SHULKER_BOX__0", 389, "Caixa de shulker cinza clara"),
	CYAN_SHULKER_BOX__0("CYAN_SHULKER_BOX__0", 390, "Caixa de shulker ciano"),
	PURPLE_SHULKER_BOX__0("PURPLE_SHULKER_BOX__0", 391, "Caixa de shulker roxa"),
	BLUE_SHULKER_BOX__0("BLUE_SHULKER_BOX__0", 392, "Caixa de shulker azul"),
	BROWN_SHULKER_BOX__0("BROWN_SHULKER_BOX__0", 393, "Caixa de shulker marrom"),
	GREEN_SHULKER_BOX__0("GREEN_SHULKER_BOX__0", 394, "Caixa de shulker verde"),
	RED_SHULKER_BOX__0("RED_SHULKER_BOX__0", 395, "Caixa de shulker vermelha"),
	BLACK_SHULKER_BOX__0("BLACK_SHULKER_BOX__0", 396, "Caixa de shulker preta"),
	WHITE_GLAZED_TERRACOTTA__0("WHITE_GLAZED_TERRACOTTA__0", 397, "Azulejo branco"),
	ORANGE_GLAZED_TERRACOTTA__0("ORANGE_GLAZED_TERRACOTTA__0", 398, "Azulejo laranja"),
	MAGENTA_GLAZED_TERRACOTTA__0("MAGENTA_GLAZED_TERRACOTTA__0", 399, "Azulejo magenta"),
	LIGHT_BLUE_GLAZED_TERRACOTTA__0("LIGHT_BLUE_GLAZED_TERRACOTTA__0", 400, "Azulejo azul claro"),
	YELLOW_GLAZED_TERRACOTTA__0("YELLOW_GLAZED_TERRACOTTA__0", 401, "Azulejo amrelo"),
	LIME_GLAZED_TERRACOTTA__0("LIME_GLAZED_TERRACOTTA__0", 402, "Azulejo verde lim\u00e3o"),
	PINK_GLAZED_TERRACOTTA__0("PINK_GLAZED_TERRACOTTA__0", 403, "Azulejo rosa"),
	GRAY_GLAZED_TERRACOTTA__0("GRAY_GLAZED_TERRACOTTA__0", 404, "Azulejo cinza"),
	SILVER_GLAZED_TERRACOTTA__0("SILVER_GLAZED_TERRACOTTA__0", 405, "Azulejo cinza claro"),
	CYAN_GLAZED_TERRACOTTA__0("CYAN_GLAZED_TERRACOTTA__0", 406, "Azulejo ciano"),
	PURPLE_GLAZED_TERRACOTTA__0("PURPLE_GLAZED_TERRACOTTA__0", 407, "Azulejo roxo"),
	BLUE_GLAZED_TERRACOTTA__0("BLUE_GLAZED_TERRACOTTA__0", 408, "Azulejo azul"),
	BROWN_GLAZED_TERRACOTTA__0("BROWN_GLAZED_TERRACOTTA__0", 409, "Azulejo marrom"),
	GREEN_GLAZED_TERRACOTTA__0("GREEN_GLAZED_TERRACOTTA__0", 410, "Azulejo verde"),
	RED_GLAZED_TERRACOTTA__0("RED_GLAZED_TERRACOTTA__0", 411, "Azulejo vermelho"),
	BLACK_GLAZED_TERRACOTTA__0("BLACK_GLAZED_TERRACOTTA__0", 412, "Azulejo preto"),
	CONCRETE__0("CONCRETE__0", 413, "Concreto branco"), CONCRETE__1("CONCRETE__1", 414, "Concreto laranja"),
	CONCRETE__2("CONCRETE__2", 415, "Concreto magenta"), CONCRETE__3("CONCRETE__3", 416, "Concreto azul claro"),
	CONCRETE__4("CONCRETE__4", 417, "Concreto amarelo"), CONCRETE__5("CONCRETE__5", 418, "Concreto verde lim\u00e3o"),
	CONCRETE__6("CONCRETE__6", 419, "Concreto rosa"), CONCRETE__7("CONCRETE__7", 420, "Concreto cinza"),
	CONCRETE__8("CONCRETE__8", 421, "Concreto cinza claro"), CONCRETE__9("CONCRETE__9", 422, "Concreto ciano"),
	CONCRETE__10("CONCRETE__10", 423, "Concreto roxo"), CONCRETE__11("CONCRETE__11", 424, "Concreto azul"),
	CONCRETE__12("CONCRETE__12", 425, "Concreto marrom"), CONCRETE__13("CONCRETE__13", 426, "Concreto verde"),
	CONCRETE__14("CONCRETE__14", 427, "Concreto vermelho"), CONCRETE__15("CONCRETE__15", 428, "Concreto preto"),
	CONCRETE_POWDER__0("CONCRETE_POWDER__0", 429, "Cimento branco"),
	CONCRETE_POWDER__1("CONCRETE_POWDER__1", 430, "Cimento laranja"),
	CONCRETE_POWDER__2("CONCRETE_POWDER__2", 431, "Cimento magenta"),
	CONCRETE_POWDER__3("CONCRETE_POWDER__3", 432, "Cimento azul claro"),
	CONCRETE_POWDER__4("CONCRETE_POWDER__4", 433, "Cimento amarelo"),
	CONCRETE_POWDER__5("CONCRETE_POWDER__5", 434, "Cimento verde lim\u00e3o"),
	CONCRETE_POWDER__6("CONCRETE_POWDER__6", 435, "Cimento rosa"),
	CONCRETE_POWDER__7("CONCRETE_POWDER__7", 436, "Cimento cinza"),
	CONCRETE_POWDER__8("CONCRETE_POWDER__8", 437, "Cimento cinza claro"),
	CONCRETE_POWDER__9("CONCRETE_POWDER__9", 438, "Cimento ciano"),
	CONCRETE_POWDER__10("CONCRETE_POWDER__10", 439, "Cimento roxo"),
	CONCRETE_POWDER__11("CONCRETE_POWDER__11", 440, "Cimento azul"),
	CONCRETE_POWDER__12("CONCRETE_POWDER__12", 441, "Cimento marrom"),
	CONCRETE_POWDER__13("CONCRETE_POWDER__13", 442, "Cimento verde"),
	CONCRETE_POWDER__14("CONCRETE_POWDER__14", 443, "Cimento vermelho"),
	CONCRETE_POWDER__15("CONCRETE_POWDER__15", 444, "Cimento preto"),
	STRUCTURE_BLOCK__0("STRUCTURE_BLOCK__0", 445, "Bloco de estrutura"),
	IRON_SPADE__0("IRON_SPADE__0", 446, "P\u00e1 de ferro"),
	IRON_PICKAXE__0("IRON_PICKAXE__0", 447, "Picareta de ferro"), IRON_AXE__0("IRON_AXE__0", 448, "Machado de ferro"),
	FLINT_AND_STEEL__0("FLINT_AND_STEEL__0", 449, "Isqueiro"), APPLE__0("APPLE__0", 450, "Ma\u00e7a"),
	BOW__0("BOW__0", 451, "Arco"), ARROW__0("ARROW__0", 452, "Flecha"), COAL__0("COAL__0", 453, "Carv\u00e3o"),
	COAL__1("COAL__1", 454, "Carv\u00e3o vegetal"), DIAMOND__0("DIAMOND__0", 455, "Diamante"),
	IRON_INGOT__0("IRON_INGOT__0", 456, "Barra de ferro"), GOLD_INGOT__0("GOLD_INGOT__0", 457, "Barra de ouro"),
	IRON_SWORD__0("IRON_SWORD__0", 458, "Espada de ferro"), WOOD_SWORD__0("WOOD_SWORD__0", 459, "Espara de madeira"),
	WOOD_SPADE__0("WOOD_SPADE__0", 460, "P\u00e1 de madeira"),
	WOOD_PICKAXE__0("WOOD_PICKAXE__0", 461, "Picareta de madeira"),
	WOOD_AXE__0("WOOD_AXE__0", 462, "Machado de madeira"), STONE_SWORD__0("STONE_SWORD__0", 463, "Espada de pedra"),
	STONE_SPADE__0("STONE_SPADE__0", 464, "P\u00e1 de pedra"),
	STONE_PICKAXE__0("STONE_PICKAXE__0", 465, "Picareta de pedra "),
	STONE_AXE__0("STONE_AXE__0", 466, "Machado de pedra"),
	DIAMOND_SWORD__0("DIAMOND_SWORD__0", 467, "Espada de diamante"),
	DIAMOND_SPADE__0("DIAMOND_SPADE__0", 468, "P\u00e1 de diamante"),
	DIAMOND_PICKAXE__0("DIAMOND_PICKAXE__0", 469, "Picareta de diamante"),
	DIAMOND_AXE__0("DIAMOND_AXE__0", 470, "Machado de diamante"), STICK__0("STICK__0", 471, "Graveto"),
	BOWL__0("BOWL__0", 472, "Tigela"), MUSHROOM_SOUP__0("MUSHROOM_SOUP__0", 473, "Ensopado de cogumelos"),
	GOLD_SWORD__0("GOLD_SWORD__0", 474, "Espada de ouro"), GOLD_SPADE__0("GOLD_SPADE__0", 475, "P\u00e1 de ouro"),
	GOLD_PICKAXE__0("GOLD_PICKAXE__0", 476, "Picareta de ouro"), GOLD_AXE__0("GOLD_AXE__0", 477, "Machado de ouro"),
	STRING__0("STRING__0", 478, "Linha"), FEATHER__0("FEATHER__0", 479, "Pena"),
	SULPHUR__0("SULPHUR__0", 480, "P\u00f3lvora"), WOOD_HOE__0("WOOD_HOE__0", 481, "Enxada de madeira"),
	STONE_HOE__0("STONE_HOE__0", 482, "Enxada de pedra"), IRON_HOE__0("IRON_HOE__0", 483, "Enxada de ferro"),
	DIAMOND_HOE__0("DIAMOND_HOE__0", 484, "Enxada de diamante"), GOLD_HOE__0("GOLD_HOE__0", 485, "Enxada de ouro"),
	SEEDS__0("SEEDS__0", 486, "Sementes"), WHEAT__0("WHEAT__0", 487, "Trigo"), BREAD__0("BREAD__0", 488, "P\u00e3o"),
	LEATHER_HELMET__0("LEATHER_HELMET__0", 489, "Capuz de couro"),
	LEATHER_CHESTPLATE__0("LEATHER_CHESTPLATE__0", 490, "T\u00fanica de couro"),
	LEATHER_LEGGINGS__0("LEATHER_LEGGINGS__0", 491, "Cal\u00e7as de couro"),
	LEATHER_BOOTS__0("LEATHER_BOOTS__0", 492, "Botas de couro"),
	CHAINMAIL_HELMET__0("CHAINMAIL_HELMET__0", 493, "Capacete de cota de malha"),
	CHAINMAIL_CHESTPLATE__0("CHAINMAIL_CHESTPLATE__0", 494, "Peitoral de cota de malha"),
	CHAINMAIL_LEGGINGS__0("CHAINMAIL_LEGGINGS__0", 495, "Cal\u00e7as de cota de malha"),
	CHAINMAIL_BOOTS__0("CHAINMAIL_BOOTS__0", 496, "Botas de cota de malha"),
	IRON_HELMET__0("IRON_HELMET__0", 497, "Capacete de ferro"),
	IRON_CHESTPLATE__0("IRON_CHESTPLATE__0", 498, "Peitoral de ferro"),
	IRON_LEGGINGS__0("IRON_LEGGINGS__0", 499, "Cal\u00e7as de ferro"),
	IRON_BOOTS__0("IRON_BOOTS__0", 500, "Botas de ferro"),
	DIAMOND_HELMET__0("DIAMOND_HELMET__0", 501, "Capacete de diamante"),
	DIAMOND_CHESTPLATE__0("DIAMOND_CHESTPLATE__0", 502, "Peitoral de diamante"),
	DIAMOND_LEGGINGS__0("DIAMOND_LEGGINGS__0", 503, "Cal\u00e7as de diamante"),
	DIAMOND_BOOTS__0("DIAMOND_BOOTS__0", 504, "Botas de diamante"),
	GOLD_HELMET__0("GOLD_HELMET__0", 505, "Capacete de ouro"),
	GOLD_CHESTPLATE__0("GOLD_CHESTPLATE__0", 506, "Peitoral de ouro"),
	GOLD_LEGGINGS__0("GOLD_LEGGINGS__0", 507, "Cal\u00e7as de ouro"),
	GOLD_BOOTS__0("GOLD_BOOTS__0", 508, "Botas de ouro"), FLINT__0("FLINT__0", 509, "Pederneira"),
	PORK__0("PORK__0", 510, "Carne de porco crua"), GRILLED_PORK__0("GRILLED_PORK__0", 511, "Carne de porco assada"),
	PAINTING__0("PAINTING__0", 512, "Pintura"), GOLDEN_APPLE__0("GOLDEN_APPLE__0", 513, "Ma\u00e7a dourada"),
	GOLDEN_APPLE__1("GOLDEN_APPLE__1", 514, "Ma\u00e7a dourada"), SIGN__0("SIGN__0", 515, "Placa"),
	WOOD_DOOR__0("WOOD_DOOR__0", 516, "Porta de carvalho"), BUCKET__0("BUCKET__0", 517, "Balde"),
	WATER_BUCKET__0("WATER_BUCKET__0", 518, "Balde de \u00e1gua"),
	LAVA_BUCKET__0("LAVA_BUCKET__0", 519, "Balde de lava"), MINECART__0("MINECART__0", 520, "Carrinho"),
	SADDLE__0("SADDLE__0", 521, "Sela"), IRON_DOOR__0("IRON_DOOR__0", 522, "Porta de ferro"),
	REDSTONE__0("REDSTONE__0", 523, "Redstone"), SNOW_BALL__0("SNOW_BALL__0", 524, "Bola de neve"),
	BOAT__0("BOAT__0", 525, "Bote"), LEATHER__0("LEATHER__0", 526, "Couro"),
	MILK_BUCKET__0("MILK_BUCKET__0", 527, "Balde de leite"), CLAY_BRICK__0("CLAY_BRICK__0", 528, "Tijolo"),
	CLAY_BALL__0("CLAY_BALL__0", 529, "Argila"), SUGAR_CANE__0("SUGAR_CANE__0", 530, "Canas de a\u00e7ucar"),
	PAPER__0("PAPER__0", 531, "Papel"), BOOK__0("BOOK__0", 532, "Livro"),
	SLIME_BALL__0("SLIME_BALL__0", 533, "Gosma de slime"),
	STORAGE_MINECART__0("STORAGE_MINECART__0", 534, "Carrinho com ba\u00fa"),
	POWERED_MINECART__0("POWERED_MINECART__0", 535, "Carrinho com fornalha"), EGG__0("EGG__0", 536, "Ovo"),
	COMPASS__0("COMPASS__0", 537, "B\u00fassola"), FISHING_ROD__0("FISHING_ROD__0", 538, "Vara de pescar"),
	WATCH__0("WATCH__0", 539, "Rel\u00f3gio"), GLOWSTONE_DUST__0("GLOWSTONE_DUST__0", 540, "P\u00f3 de pedra luminosa"),
	RAW_FISH__0("RAW_FISH__0", 541, "Peixe cru"), RAW_FISH__1("RAW_FISH__1", 542, "Salm\u00e3o cru"),
	RAW_FISH__2("RAW_FISH__2", 543, "Peixe-palha\u00e7o"), RAW_FISH__3("RAW_FISH__3", 544, "Baiacu"),
	COOKED_FISH__0("COOKED_FISH__0", 545, "Peixe assado"), COOKED_FISH__1("COOKED_FISH__1", 546, "Salm\u00e3o assado"),
	INK_SACK__0("INK_SACK__0", 547, "Bolsa de tinta"), INK_SACK__1("INK_SACK__1", 548, "Vermelho da rosa"),
	INK_SACK__2("INK_SACK__2", 549, "Verde do cacto"), INK_SACK__3("INK_SACK__3", 550, "Sementes de cacau"),
	INK_SACK__4("INK_SACK__4", 551, "L\u00e1pis-laz\u00fali"), INK_SACK__5("INK_SACK__5", 552, "Corante lil\u00e1s"),
	INK_SACK__6("INK_SACK__6", 553, "Corante ciano"), INK_SACK__7("INK_SACK__7", 554, "Corante cinza claro"),
	INK_SACK__8("INK_SACK__8", 555, "Corante cinza"), INK_SACK__9("INK_SACK__9", 556, "Corante rosa"),
	INK_SACK__10("INK_SACK__10", 557, "Corante verde lim\u00e3o"),
	INK_SACK__11("INK_SACK__11", 558, "Amarelo do dente-de-le\u00e3o"),
	INK_SACK__12("INK_SACK__12", 559, "Corante azul claro"), INK_SACK__13("INK_SACK__13", 560, "Corante magenta"),
	INK_SACK__14("INK_SACK__14", 561, "Corante laranja"), INK_SACK__15("INK_SACK__15", 562, "Farinha de osso"),
	BONE__0("BONE__0", 563, "Osso"), SUGAR__0("SUGAR__0", 564, "A\u00e7\u00facar"), CAKE__0("CAKE__0", 565, "Bolo"),
	BED__0("BED__0", 566, "Cama"), DIODE__0("DIODE__0", 567, "Repetidor de redstone"),
	COOKIE__0("COOKIE__0", 568, "Biscoito"), MAP__0("MAP__0", 569, "Mapa"),
	SHEARS__0("SHEARS__0", 570, "Tesour\u00e3o"), MELON__0("MELON__0", 571, "Melancia"),
	PUMPKIN_SEEDS__0("PUMPKIN_SEEDS__0", 572, "Sementes de ab\u00f3bora"),
	MELON_SEEDS__0("MELON_SEEDS__0", 573, "Sementes de melancia"), RAW_BEEF__0("RAW_BEEF__0", 574, "Bife cru"),
	COOKED_BEEF__0("COOKED_BEEF__0", 575, "Fil\u00e9"), RAW_CHICKEN__0("RAW_CHICKEN__0", 576, "Frango cru"),
	COOKED_CHICKEN__0("COOKED_CHICKEN__0", 577, "Frango assado"),
	ROTTEN_FLESH__0("ROTTEN_FLESH__0", 578, "Carne podre"), ENDER_PEARL__0("ENDER_PEARL__0", 579, "P\u00e9rola do fim"),
	BLAZE_ROD__0("BLAZE_ROD__0", 580, "Vara incandescente"),
	GHAST_TEAR__0("GHAST_TEAR__0", 581, "L\u00e1grima de ghast"),
	GOLD_NUGGET__0("GOLD_NUGGET__0", 582, "Pepita de ouro"), NETHER_STALK__0("NETHER_STALK__0", 583, "Fungo do nether"),
	POTION__0("POTION__0", 584, "Po\u00e7\u00e3o"), GLASS_BOTTLE__0("GLASS_BOTTLE__0", 585, "Frasco de vidro"),
	SPIDER_EYE__0("SPIDER_EYE__0", 586, "Olho de aranha"),
	FERMENTED_SPIDER_EYE__0("FERMENTED_SPIDER_EYE__0", 587, "Olho de aranha fermentado"),
	BLAZE_POWDER__0("BLAZE_POWDER__0", 588, "P\u00f3 de blaze"),
	MAGMA_CREAM__0("MAGMA_CREAM__0", 589, "Creme de magma"),
	BREWING_STAND_ITEM__0("BREWING_STAND_ITEM__0", 590, "Suporte de po\u00e7\u00f5es"),
	CAULDRON_ITEM__0("CAULDRON_ITEM__0", 591, "Caldeir\u00e3o"), EYE_OF_ENDER__0("EYE_OF_ENDER__0", 592, "Olho do fim"),
	SPECKLED_MELON__0("SPECKLED_MELON__0", 593, "Melancia reluzente"),
	MONSTER_EGG__0("MONSTER_EGG__0", 594, "Ovo de monstro"),
	EXP_BOTTLE__0("EXP_BOTTLE__0", 595, "Frasco de experi\u00eancia"), FIREBALL__0("FIREBALL__0", 596, "Bola de fogo"),
	BOOK_AND_QUILL__0("BOOK_AND_QUILL__0", 597, "Pena e livro"),
	WRITTEN_BOOK__0("WRITTEN_BOOK__0", 598, "Livro escrito"), EMERALD__0("EMERALD__0", 599, "Esmeralda"),
	ITEM_FRAME__0("ITEM_FRAME__0", 600, "Moldura"), FLOWER_POT_ITEM__0("FLOWER_POT_ITEM__0", 601, "Vaso de flor"),
	CARROT_ITEM__0("CARROT_ITEM__0", 602, "Cenoura"), POTATO_ITEM__0("POTATO_ITEM__0", 603, "Batata"),
	BAKED_POTATO__0("BAKED_POTATO__0", 604, "Batata assada"),
	POISONOUS_POTATO__0("POISONOUS_POTATO__0", 605, "Batata venenosa"),
	EMPTY_MAP__0("EMPTY_MAP__0", 606, "Mapa em branco"), GOLDEN_CARROT__0("GOLDEN_CARROT__0", 607, "Cenoura dourada"),
	SKULL_ITEM__0("SKULL_ITEM__0", 608, "Cr\u00e2nio de esqueleto"),
	SKULL_ITEM__1("SKULL_ITEM__1", 609, "Cr\u00e2nio de esqueleto whiter"),
	SKULL_ITEM__2("SKULL_ITEM__2", 610, "Cabe\u00e7a de zumbi"), SKULL_ITEM__3("SKULL_ITEM__3", 611, "Cabe\u00e7a"),
	SKULL_ITEM__4("SKULL_ITEM__4", 612, "Cabe\u00e7a de creeper"),
	SKULL_ITEM__5("SKULL_ITEM__5", 613, "Cabe\u00e7a de drag\u00e3o"),
	CARROT_STICK__0("CARROT_STICK__0", 614, "Vara de pesca com cenoura"),
	NETHER_STAR__0("NETHER_STAR__0", 615, "Estrela do Nether"),
	PUMPKIN_PIE__0("PUMPKIN_PIE__0", 616, "Torta de ab\u00f3bora"),
	FIREWORK__0("FIREWORK__0", 617, "Fogos de artif\u00edcio"),
	FIREWORK_CHARGE__0("FIREWORK_CHARGE__0", 618, "Estrela de fogos de artif\u00edcio"),
	ENCHANTED_BOOK__0("ENCHANTED_BOOK__0", 619, "Livro encantado"),
	REDSTONE_COMPARATOR__0("REDSTONE_COMPARATOR__0", 620, "Comparador de redstone"),
	NETHER_BRICK_ITEM__0("NETHER_BRICK_ITEM__0", 621, "Tijolo do Nether"),
	QUARTZ__0("QUARTZ__0", 622, "Quartzo do Nether"),
	EXPLOSIVE_MINECART__0("EXPLOSIVE_MINECART__0", 623, "Carrinho com dinamite"),
	HOPPER_MINECART__0("HOPPER_MINECART__0", 624, "Carrinho com funil"),
	PRISMARINE_SHARD__0("PRISMARINE_SHARD__0", 625, "Fragmento de prismarinho"),
	PRISMARINE_CRYSTALS__0("PRISMARINE_CRYSTALS__0", 626, "Cristais de prismarinho"),
	RABBIT__0("RABBIT__0", 627, "Coelho cru"), COOKED_RABBIT__0("COOKED_RABBIT__0", 628, "Coelho assado"),
	RABBIT_STEW__0("RABBIT_STEW__0", 629, "Ensopado de coelho"),
	RABBIT_FOOT__0("RABBIT_FOOT__0", 630, "P\u00e9 de coelho"), RABBIT_HIDE__0("RABBIT_HIDE__0", 631, "Pele de coelho"),
	ARMOR_STAND__0("ARMOR_STAND__0", 632, "Suporte de Armaduras"),
	IRON_BARDING__0("IRON_BARDING__0", 633, "Armadura de ferro para cavalo"),
	GOLD_BARDING__0("GOLD_BARDING__0", 634, "Armadura de ouro para cavalo"),
	DIAMOND_BARDING__0("DIAMOND_BARDING__0", 635, "Armadura de diamante para cavalo"),
	LEASH__0("LEASH__0", 636, "La\u00e7o"), NAME_TAG__0("NAME_TAG__0", 637, "Etiqueta"),
	COMMAND_MINECART__0("COMMAND_MINECART__0", 638, "Carrinho com bloco de comando"),
	MUTTON__0("MUTTON__0", 639, "Carneiro cru"), COOKED_MUTTON__0("COOKED_MUTTON__0", 640, "Carneiro assado"),
	BANNER__0("BANNER__0", 641, "Estandarte preto"), BANNER__1("BANNER__1", 642, "Estandarte vermelho"),
	BANNER__2("BANNER__2", 643, "Estandarte verde"), BANNER__3("BANNER__3", 644, "Estandarte marrom"),
	BANNER__4("BANNER__4", 645, "Estandarte azul"), BANNER__5("BANNER__5", 646, "Estandarte lil\u00e1s"),
	BANNER__6("BANNER__6", 647, "Estandarte ciano"), BANNER__7("BANNER__7", 648, "Estandarte cinza claro"),
	BANNER__8("BANNER__8", 649, "Estandarte cinza"), BANNER__9("BANNER__9", 650, "Estandarte rosa"),
	BANNER__10("BANNER__10", 651, "Estandarte verde lim\u00e3o"), BANNER__11("BANNER__11", 652, "Estandarte amarelo"),
	BANNER__12("BANNER__12", 653, "Estandarte azul claro"), BANNER__13("BANNER__13", 654, "Estandarte magenta"),
	BANNER__14("BANNER__14", 655, "Estandarte laranja"), BANNER__15("BANNER__15", 656, "Estandarte branco"),
	END_CRYSTAL__0("END_CRYSTAL__0", 657, "Cristal do end"),
	SPRUCE_DOOR_ITEM__0("SPRUCE_DOOR_ITEM__0", 658, "Porta de pinheiro"),
	BIRCH_DOOR_ITEM__0("BIRCH_DOOR_ITEM__0", 659, "Porta de eucalipto"),
	JUNGLE_DOOR_ITEM__0("JUNGLE_DOOR_ITEM__0", 660, "Porta de madeira da selva"),
	ACACIA_DOOR_ITEM__0("ACACIA_DOOR_ITEM__0", 661, "Porta de ac\u00e1cia"),
	DARK_OAK_DOOR_ITEM__0("DARK_OAK_DOOR_ITEM__0", 662, "Porta de carvalho escuro"),
	CHORUS_FRUIT__0("CHORUS_FRUIT__0", 663, "Fruta do coro"),
	CHORUS_FRUIT_POPPED__0("CHORUS_FRUIT_POPPED__0", 664, "Fruta do coro estourada"),
	BEETROOT__0("BEETROOT__0", 665, "Beterraba"), BEETROOT_SEEDS__0("BEETROOT_SEEDS__0", 666, "Sementes de beterraba"),
	BEETROOT_SOUP__0("BEETROOT_SOUP__0", 667, "Sopa de beterraba"),
	DRAGONS_BREATH__0("DRAGONS_BREATH__0", 668, "Bafo de drag\u00e3o"),
	SPLASH_POTION__0("SPLASH_POTION__0", 669, "Po\u00e7\u00e3o arremess\u00e1vel"),
	SPECTRAL_ARROW__0("SPECTRAL_ARROW__0", 670, "Flecha espectral"),
	TIPPED_ARROW__0("TIPPED_ARROW__0", 671, "Flecha especial"),
	LINGERING_POTION__0("LINGERING_POTION__0", 672, "Po\u00e7\u00e3o prolongada"),
	SHIELD__0("SHIELD__0", 673, "Escudo"), ELYTRA__0("ELYTRA__0", 674, "\u00c9litros"),
	BOAT_SPRUCE__0("BOAT_SPRUCE__0", 675, "Bote de pinheiro"), BOAT_BIRCH__0("BOAT_BIRCH__0", 676, "Bote eucalipto"),
	BOAT_JUNGLE__0("BOAT_JUNGLE__0", 677, "Bote de madeira da selva"),
	BOAT_ACACIA__0("BOAT_ACACIA__0", 678, "Bote de ac\u00e1cia"),
	BOAT_DARK_OAK__0("BOAT_DARK_OAK__0", 679, "Bote de carvalho escuro"),
	TOTEM__0("TOTEM__0", 680, "Totem da imortalidade"), SHULKER_SHELL__0("SHULKER_SHELL__0", 681, "Casco de shulker"),
	IRON_NUGGET__0("IRON_NUGGET__0", 682, "Pepita de ferro"),
	KNOWLEDGE_BOOK__0("KNOWLEDGE_BOOK__0", 683, "Livro do conhecimento"),
	GOLD_RECORD__0("GOLD_RECORD__0", 684, "Disco de m\u00fasica"),
	GREEN_RECORD__0("GREEN_RECORD__0", 685, "Disco de m\u00fasica"),
	RECORD_3__0("RECORD_3__0", 686, "Disco de m\u00fasica"), RECORD_4__0("RECORD_4__0", 687, "Disco de m\u00fasica"),
	RECORD_5__0("RECORD_5__0", 688, "Disco de m\u00fasica"), RECORD_6__0("RECORD_6__0", 689, "Disco de m\u00fasica"),
	RECORD_7__0("RECORD_7__0", 690, "Disco de m\u00fasica"), RECORD_8__0("RECORD_8__0", 691, "Disco de m\u00fasica"),
	RECORD_9__0("RECORD_9__0", 692, "Disco de m\u00fasica"), RECORD_10__0("RECORD_10__0", 693, "Disco de m\u00fasica"),
	RECORD_11__0("RECORD_11__0", 694, "Disco de m\u00fasica"),
	RECORD_12__0("RECORD_12__0", 695, "Disco de m\u00fasica");

	private String name;

	private ItemName(final String s, final int n, final String name) {
		this.name = name;
	}

	public String getName() {
		return this.name;
	}

	public static ItemName valueOf(final ItemStack item) {
		try {
			return valueOf(String.valueOf(item.getType().name()) + "__" + item.getDurability());
		} catch (Exception | Error ex) {
			return valueOf(String.valueOf(item.getType().name()) + "__0");
		}
	}

	public static ItemName valueOf(final String name, final short durability) {
		try {
			return valueOf(String.valueOf(name) + "__" + durability);
		} catch (Exception | Error ex) {
			return valueOf(String.valueOf(name) + "__0");
		}
	}

	public static ItemName valueOf(final String name, final byte data) {
		try {
			return valueOf(String.valueOf(name) + "__" + data);
		} catch (Exception | Error ex) {
			return valueOf(String.valueOf(name) + "__0");
		}
	}

	public static ItemName valueOf(final Material material, final byte data) {
		try {
			return valueOf(String.valueOf(material.name()) + "__" + data);
		} catch (Exception | Error ex) {
			return valueOf(String.valueOf(material.name()) + "__0");
		}
	}

	public static ItemName valueOf(final Material material) {
		return valueOf(String.valueOf(material.name()) + "__0");
	}

	public static ItemName valueOf(final Item item) {
		return valueOf(item.getItemStack());
	}

	@SuppressWarnings("deprecation")
	public static ItemName valueOf(final Block block) {
		return valueOf(block.getType(), block.getData());
	}
}
